spring:
    application:
        name: simple-crud

    datasource:
        url: jdbc:postgresql://localhost:5432/simple_crud
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update